server:
  port: 8082

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/todolist}
  datasource:
    url: jdbc:mysql://localhost:3306/register_user
    username: root
    password: krisara124
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernation:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect

